name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1

      - name: Build the extension
        run: |
          set -eux
          pip install .[dev,test]

          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "ipylab.*OK"
          python -m jupyterlab.browser_check
          pytest -v

      - name: Package the extension
        run: |
          set -eux

          hatch build
          pip uninstall -y "ipylab" jupyterlab

      - name: Upload extension packages
        uses: actions/upload-artifact@v4
        with:
          name: extension-artifacts
          path: dist/ipylab*
          if-no-files-found: error

  test_isolated:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
      - uses: actions/download-artifact@v4
        with:
          name: extension-artifacts
      - name: Install and Test
        run: |
          set -eux
          # Remove NodeJS, twice to take care of system and locally installed node versions.
          sudo rm -rf $(which node)
          sudo rm -rf $(which node)

          pip install ipylab*.whl


          jupyter labextension list
          jupyter labextension list 2>&1 | grep -ie "ipylab.*OK"
          python -m jupyterlab.browser_check --no-browser-test

  check_links:
    name: Check Links
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
      - uses: jupyterlab/maintainer-tools/.github/actions/check-links@v1
